"""empty message

Revision ID: 1f164ee2a81f
Revises: f162a478ca0f
Create Date: 2018-06-27 02:39:22.844075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f164ee2a81f'
down_revision = 'f162a478ca0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    # ### end Alembic commands ###
